// GENERATED by firepack — do not edit.
// Source: example/firepack.yaml
//
// Regenerate via:
//   dart run firepack:firepack regen --target models --spec <path>
//
// To change a field, edit the spec, then regenerate. Hand-edits here
// are overwritten on the next `firepack regen`.

class Comment {
  final String id;
  final String organizationId;
  final String postId;
  final String authorId;
  final String body;
  final DateTime createdAt;

  const Comment({
    required this.id,
    required this.organizationId,
    required this.postId,
    required this.authorId,
    required this.body,
    required this.createdAt,
  });

  Comment copyWith({
    String? id,
    String? organizationId,
    String? postId,
    String? authorId,
    String? body,
    DateTime? createdAt,
  }) =>
      Comment(
        id: id ?? this.id,
        organizationId: organizationId ?? this.organizationId,
        postId: postId ?? this.postId,
        authorId: authorId ?? this.authorId,
        body: body ?? this.body,
        createdAt: createdAt ?? this.createdAt,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'organizationId': organizationId,
        'postId': postId,
        'authorId': authorId,
        'body': body,
        'createdAt': createdAt.toIso8601String(),
      };

  factory Comment.fromJson(Map<String, dynamic> json) => Comment(
        id: json['id'] as String,
        organizationId: json['organizationId'] as String,
        postId: json['postId'] as String,
        authorId: json['authorId'] as String,
        body: json['body'] as String,
        createdAt: DateTime.parse(json['createdAt'] as String),
      );

  Map<String, dynamic> toFirestore() => {
        'id': id,
        'organizationId': organizationId,
        'postId': postId,
        'authorId': authorId,
        'body': body,
        'createdAt': createdAt,
      };

  factory Comment.fromFirestore(Map<String, dynamic> data) => Comment(
        id: data['id'] as String,
        organizationId: data['organizationId'] as String,
        postId: data['postId'] as String,
        authorId: data['authorId'] as String,
        body: data['body'] as String,
        createdAt: _toDateTime(data['createdAt']),
      );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Comment &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          organizationId == other.organizationId &&
          postId == other.postId &&
          authorId == other.authorId &&
          body == other.body &&
          createdAt == other.createdAt;

  @override
  int get hashCode =>
      Object.hash(id, organizationId, postId, authorId, body, createdAt);
}

// Duck-typed Timestamp → DateTime conversion. Accepts whatever
// Firestore returns (Timestamp), or already-DateTime values from
// in-memory tests, or ISO strings from JSON. Avoids importing
// cloud_firestore here so models stay framework-agnostic.
DateTime _toDateTime(dynamic raw) {
  if (raw is DateTime) return raw;
  if (raw is String) return DateTime.parse(raw);
  // Timestamp from cloud_firestore — duck-typed via toDate().
  return (raw as dynamic).toDate() as DateTime;
}
