// GENERATED by firepack — do not edit.
// Source: example/firepack.yaml
//
// Regenerate via:
//   dart run firepack:firepack regen --target models --spec <path>
//
// To change a field, edit the spec, then regenerate. Hand-edits here
// are overwritten on the next `firepack regen`.

// Shared enums — referenced from models via `enum[<Name>]`.
// Each enum gets a `<Name>Json` extension with wireFormat-aware
// toJson()/fromJson() so the model layer never touches naming.

enum PostStatus { draft, published, archived }

extension PostStatusJson on PostStatus {
  String toJson() => name;
  static PostStatus fromJson(String s) => PostStatus.values.byName(s);
}

enum UserRole { admin, author, reader }

extension UserRoleJson on UserRole {
  String toJson() => name;
  static UserRole fromJson(String s) => UserRole.values.byName(s);
}
