// GENERATED by firepack — do not edit.
// Source: example/firepack.yaml
//
// Regenerate via:
//   dart run firepack:firepack regen --target models --spec <path>
//
// To change a field, edit the spec, then regenerate. Hand-edits here
// are overwritten on the next `firepack regen`.

class LinkPreview {
  final String url;
  final String title;
  final String? description;
  final String? imageUrl;

  const LinkPreview({
    required this.url,
    required this.title,
    this.description,
    this.imageUrl,
  });

  LinkPreview copyWith({
    String? url,
    String? title,
    String? description,
    String? imageUrl,
  }) =>
      LinkPreview(
        url: url ?? this.url,
        title: title ?? this.title,
        description: description ?? this.description,
        imageUrl: imageUrl ?? this.imageUrl,
      );

  Map<String, dynamic> toJson() => {
        'url': url,
        'title': title,
        if (description != null) 'description': description,
        if (imageUrl != null) 'imageUrl': imageUrl,
      };

  factory LinkPreview.fromJson(Map<String, dynamic> json) => LinkPreview(
        url: json['url'] as String,
        title: json['title'] as String,
        description: json['description'] as String?,
        imageUrl: json['imageUrl'] as String?,
      );

  Map<String, dynamic> toFirestore() => {
        'url': url,
        'title': title,
        if (description != null) 'description': description,
        if (imageUrl != null) 'imageUrl': imageUrl,
      };

  factory LinkPreview.fromFirestore(Map<String, dynamic> data) => LinkPreview(
        url: data['url'] as String,
        title: data['title'] as String,
        description: data['description'] as String?,
        imageUrl: data['imageUrl'] as String?,
      );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LinkPreview &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          title == other.title &&
          description == other.description &&
          imageUrl == other.imageUrl;

  @override
  int get hashCode => Object.hash(url, title, description, imageUrl);
}
