// GENERATED by firepack — do not edit.
// Source: example/firepack.yaml
//
// Regenerate via:
//   dart run firepack:firepack regen --target models --spec <path>
//
// To change a field, edit the spec, then regenerate. Hand-edits here
// are overwritten on the next `firepack regen`.

class Organization {
  final String id;
  final String name;
  final DateTime createdAt;

  const Organization({
    required this.id,
    required this.name,
    required this.createdAt,
  });

  Organization copyWith({
    String? id,
    String? name,
    DateTime? createdAt,
  }) =>
      Organization(
        id: id ?? this.id,
        name: name ?? this.name,
        createdAt: createdAt ?? this.createdAt,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
        'createdAt': createdAt.toIso8601String(),
      };

  factory Organization.fromJson(Map<String, dynamic> json) => Organization(
        id: json['id'] as String,
        name: json['name'] as String,
        createdAt: DateTime.parse(json['createdAt'] as String),
      );

  Map<String, dynamic> toFirestore() => {
        'id': id,
        'name': name,
        'createdAt': createdAt,
      };

  factory Organization.fromFirestore(Map<String, dynamic> data) => Organization(
        id: data['id'] as String,
        name: data['name'] as String,
        createdAt: _toDateTime(data['createdAt']),
      );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Organization &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          createdAt == other.createdAt;

  @override
  int get hashCode => Object.hash(id, name, createdAt);
}

// Duck-typed Timestamp → DateTime conversion. Accepts whatever
// Firestore returns (Timestamp), or already-DateTime values from
// in-memory tests, or ISO strings from JSON. Avoids importing
// cloud_firestore here so models stay framework-agnostic.
DateTime _toDateTime(dynamic raw) {
  if (raw is DateTime) return raw;
  if (raw is String) return DateTime.parse(raw);
  // Timestamp from cloud_firestore — duck-typed via toDate().
  return (raw as dynamic).toDate() as DateTime;
}
