// GENERATED by firepack — do not edit.
// Source: example/firepack.yaml
//
// Regenerate via:
//   dart run firepack:firepack regen --target models --spec <path>
//
// To change a field, edit the spec, then regenerate. Hand-edits here
// are overwritten on the next `firepack regen`.

import 'link_preview.dart';
import 'enums.dart';

class Post {
  final String id;
  final String organizationId;
  final String authorId;
  final String title;
  final String body;
  final String? coverImage;
  final List<String> attachments;
  final LinkPreview? linkPreview;
  final PostStatus status;
  final DateTime createdAt;
  final DateTime? publishedAt;

  const Post({
    required this.id,
    required this.organizationId,
    required this.authorId,
    required this.title,
    required this.body,
    this.coverImage,
    this.attachments = const [],
    this.linkPreview,
    this.status = PostStatus.draft,
    required this.createdAt,
    this.publishedAt,
  });

  Post copyWith({
    String? id,
    String? organizationId,
    String? authorId,
    String? title,
    String? body,
    String? coverImage,
    List<String>? attachments,
    LinkPreview? linkPreview,
    PostStatus? status,
    DateTime? createdAt,
    DateTime? publishedAt,
  }) => Post(
    id: id ?? this.id,
    organizationId: organizationId ?? this.organizationId,
    authorId: authorId ?? this.authorId,
    title: title ?? this.title,
    body: body ?? this.body,
    coverImage: coverImage ?? this.coverImage,
    attachments: attachments ?? this.attachments,
    linkPreview: linkPreview ?? this.linkPreview,
    status: status ?? this.status,
    createdAt: createdAt ?? this.createdAt,
    publishedAt: publishedAt ?? this.publishedAt,
  );

  Map<String, dynamic> toJson() => {
    'id': id,
    'organizationId': organizationId,
    'authorId': authorId,
    'title': title,
    'body': body,
    if (coverImage != null) 'coverImage': coverImage,
    'attachments': attachments,
    if (linkPreview != null) 'linkPreview': linkPreview?.toJson(),
    'status': status.toJson(),
    'createdAt': createdAt.toIso8601String(),
    if (publishedAt != null) 'publishedAt': publishedAt?.toIso8601String(),
  };

  factory Post.fromJson(Map<String, dynamic> json) => Post(
    id: json['id'] as String,
    organizationId: json['organizationId'] as String,
    authorId: json['authorId'] as String,
    title: json['title'] as String,
    body: json['body'] as String,
    coverImage: json['coverImage'] as String?,
    attachments: json['attachments'] == null ? const [] : (json['attachments'] as List).cast<String>(),
    linkPreview: json['linkPreview'] == null ? null : LinkPreview.fromJson((json['linkPreview'] as Map).cast<String, dynamic>()),
    status: json['status'] == null ? PostStatus.draft : PostStatusJson.fromJson(json['status'] as String),
    createdAt: DateTime.parse(json['createdAt'] as String),
    publishedAt: json['publishedAt'] == null ? null : DateTime.parse(json['publishedAt'] as String),
  );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Post &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          organizationId == other.organizationId &&
          authorId == other.authorId &&
          title == other.title &&
          body == other.body &&
          coverImage == other.coverImage &&
          _listEq(attachments, other.attachments) &&
          linkPreview == other.linkPreview &&
          status == other.status &&
          createdAt == other.createdAt &&
          publishedAt == other.publishedAt;

  @override
  int get hashCode => Object.hash(
        id,
        organizationId,
        authorId,
        title,
        body,
        coverImage,
        Object.hashAll(attachments),
        linkPreview,
        status,
        createdAt,
        publishedAt
      );
}

// Deep list equality — private to this file (no external deps).
bool _listEq(List<dynamic>? a, List<dynamic>? b) {
  if (identical(a, b)) return true;
  if (a == null || b == null) return false;
  if (a.length != b.length) return false;
  for (var i = 0; i < a.length; i++) {
    if (a[i] != b[i]) return false;
  }
  return true;
}
