// GENERATED by firepack — do not edit.
// Source: example/firepack.yaml
//
// Regenerate via:
//   dart run firepack:firepack regen --target models --spec <path>
//
// To change a field, edit the spec, then regenerate. Hand-edits here
// are overwritten on the next `firepack regen`.

import 'enums.dart';

class User {
  final String id;
  final String organizationId;
  final String displayName;
  final String email;
  final UserRole role;

  const User({
    required this.id,
    required this.organizationId,
    required this.displayName,
    required this.email,
    this.role = UserRole.reader,
  });

  User copyWith({
    String? id,
    String? organizationId,
    String? displayName,
    String? email,
    UserRole? role,
  }) => User(
    id: id ?? this.id,
    organizationId: organizationId ?? this.organizationId,
    displayName: displayName ?? this.displayName,
    email: email ?? this.email,
    role: role ?? this.role,
  );

  Map<String, dynamic> toJson() => {
    'id': id,
    'organizationId': organizationId,
    'displayName': displayName,
    'email': email,
    'role': role.toJson(),
  };

  factory User.fromJson(Map<String, dynamic> json) => User(
    id: json['id'] as String,
    organizationId: json['organizationId'] as String,
    displayName: json['displayName'] as String,
    email: json['email'] as String,
    role: json['role'] == null ? UserRole.reader : UserRoleJson.fromJson(json['role'] as String),
  );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is User &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          organizationId == other.organizationId &&
          displayName == other.displayName &&
          email == other.email &&
          role == other.role;

  @override
  int get hashCode => Object.hash(
        id,
        organizationId,
        displayName,
        email,
        role
      );
}
