// GENERATED by firepack — do not edit.
// Source: firepack.yaml
//
// Regenerate via:
//   dart run firepack:firepack regen --target firestore_provider --spec <path>
//
// Hand-edits here are overwritten on the next `firepack regen`.

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// Single-seam Provider for FirebaseFirestore.
///
/// Override in tests / multi-DB / staging environments:
/// ```dart
/// ProviderScope(
///   overrides: [
///     firestoreProvider.overrideWithValue(fakeFirestore),
///   ],
///   child: const MyApp(),
/// )
/// ```
///
/// Every generated repository depends on this provider — overriding it
/// once swaps the underlying instance for all of them.
final firestoreProvider = Provider<FirebaseFirestore>(
  (_) => FirebaseFirestore.instance,
);
