// GENERATED by firepack — do not edit.
// Source: firepack.yaml
//
// Regenerate via:
//   dart run firepack:firepack regen --target paths --spec <path>
//
// Hand-edits here are overwritten on the next `firepack regen`.

/// Typed Firestore collection paths. Repository codegen
/// references `FirestorePaths.<name>` so a renamed collection
/// in the spec breaks the build, not the runtime.
class FirestorePaths {
  FirestorePaths._();

  static const String organizations = 'organizations';

  static const String users = 'users';

  static const String posts = 'posts';

  static const String comments = 'comments';
}
