// GENERATED by firepack — do not edit.
// Source: firepack.yaml
//
// Regenerate via:
//   firepack regen --target storage --spec <path>
//
// To change a Storage bucket's path or content types, edit the spec,
// then regenerate. Hand-edits here are overwritten on the next run.

/// Typed Cloud Storage path helpers, one method per declared
/// bucket in the firepack spec. Use these instead of hand-typed
/// strings — drift between upload code, read code, and rules
/// becomes impossible.
class StoragePaths {
  const StoragePaths._();

  /// Path for `postCovers` bucket. Template:
  /// `covers/{organizationId}/{postId}.jpg`
  /// Tenant variable: `organizationId`.
  static String postCovers({
    required String organizationId,
    required String postId,
  }) =>
      'covers/$organizationId/$postId.jpg';

  /// MIME types accepted by the `postCovers` bucket.
  static const List<String> postCoversContentTypes = [
    'image/jpeg',
    'image/png'
  ];

  /// Path for `attachments` bucket. Template:
  /// `attachments/{organizationId}/{postId}/{attachmentId}`
  /// Tenant variable: `organizationId`.
  static String attachments({
    required String organizationId,
    required String postId,
    required String attachmentId,
  }) =>
      'attachments/$organizationId/$postId/$attachmentId';

  /// MIME types accepted by the `attachments` bucket.
  static const List<String> attachmentsContentTypes = [
    'application/pdf',
    'image/jpeg',
    'image/png'
  ];
}
