import '../spec/spec.dart';

/// Generates a single Dart model file per collection.
///
/// **Output shape (v0.0.5, minimal):**
/// - one immutable Dart class with `final` fields
/// - const constructor with named parameters (required where the spec
///   marked the field required, defaulted where the spec gave a default)
/// - `toJson()` returning `Map<String, dynamic>` — DateTime → ISO string,
///   enums → `.name`, omit-if-null for optional fields
/// - `factory fromJson(...)` — DateTime.parse, enum.values.byName,
///   defaults applied for absent or null fields
/// - generated `enum` classes for every `enum`-typed field, named
///   `<ClassName><FieldNamePascal>` (e.g. `ErrorReportLevel`)
///
/// **Not yet (v0.0.5):**
/// - `copyWith` — most consumers can rebuild via constructor; added in
///   v0.0.6 once the `editing-flows-want-it` pain is real
/// - `==` / `hashCode` — same reasoning
/// - nested freezed-style types (`list[DraftTask]`) — currently emitted
///   as `List<dynamic>` because the spec doesn't formally model nested
///   types yet; lifted in a future iteration as the pattern repeats
String generateDartModel(CollectionSpec collection, {String? sourceFile}) {
  final cls = _classNameFor(collection.name);
  final buf = StringBuffer();

  buf.writeln(_header(sourceFile));
  buf.writeln();

  // Generated enum classes — one per enum-typed field, declared first
  // so the main class can reference them as types.
  for (final f in collection.fields.values) {
    if (f.type == FieldType.enum_) {
      buf.writeln(_emitEnum(cls, f));
      buf.writeln();
    }
  }

  buf.writeln('class $cls {');
  for (final f in collection.fields.values) {
    buf.writeln('  final ${_dartType(cls, f)} ${f.name};');
  }
  buf.writeln();

  // const constructor
  buf.writeln('  const $cls({');
  for (final f in collection.fields.values) {
    final isReq = f.required || f.primaryKey;
    final hasDefault = f.defaultValue != null;
    final keyword = isReq && !hasDefault ? 'required ' : '';
    final defaultPart = hasDefault ? ' = ${_dartLiteral(f.defaultValue, f, cls)}' : '';
    buf.writeln('    $keyword'
        'this.${f.name}'
        '$defaultPart,');
  }
  buf.writeln('  });');
  buf.writeln();

  // toJson
  buf.writeln('  Map<String, dynamic> toJson() => {');
  for (final f in collection.fields.values) {
    final omitIfNull = f.optional && !f.required;
    final access = f.name;
    final ser = _toJsonExpr(access, f);
    if (omitIfNull) {
      buf.writeln("    if ($access != null) '${f.name}': $ser,");
    } else {
      buf.writeln("    '${f.name}': $ser,");
    }
  }
  buf.writeln('  };');
  buf.writeln();

  // fromJson
  buf.writeln('  factory $cls.fromJson(Map<String, dynamic> json) => $cls(');
  for (final f in collection.fields.values) {
    final readExpr = _fromJsonExpr("json['${f.name}']", f, cls);
    buf.writeln('    ${f.name}: $readExpr,');
  }
  buf.writeln('  );');
  buf.writeln('}');

  return buf.toString();
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

String _header(String? sourceFile) {
  final src = sourceFile ?? 'firepack.yaml';
  return '''// GENERATED by firepack — do not edit.
// Source: $src
//
// Regenerate via:
//   dart run firepack:firepack regen --target models --spec <path>
//
// To change a field, edit the spec, then regenerate. Hand-edits here
// are overwritten on the next `firepack regen`.''';
}

String _classNameFor(String collectionName) {
  // workBriefs → WorkBrief, errorReports → ErrorReport, users → User.
  final singular = collectionName.endsWith('s')
      ? collectionName.substring(0, collectionName.length - 1)
      : collectionName;
  return singular[0].toUpperCase() + singular.substring(1);
}

String _enumNameFor(String className, String fieldName) {
  // ErrorReport + level → ErrorReportLevel
  return className + fieldName[0].toUpperCase() + fieldName.substring(1);
}

String _emitEnum(String className, FieldSpec f) {
  final name = _enumNameFor(className, f.name);
  final values = f.enumValues!.join(', ');
  return 'enum $name { $values }';
}

String _dartType(String className, FieldSpec f) {
  String base;
  switch (f.type) {
    case FieldType.string:
      base = 'String';
    case FieldType.int_:
      base = 'int';
    case FieldType.double_:
      base = 'double';
    case FieldType.bool_:
      base = 'bool';
    case FieldType.dateTime:
      base = 'DateTime';
    case FieldType.enum_:
      base = _enumNameFor(className, f.name);
    case FieldType.ref:
      // Refs serialise as doc-id strings.
      base = 'String';
    case FieldType.list:
      // We don't track structured item types yet — fall back to the
      // most-common case (List<String>) when item is string or ref,
      // List<dynamic> otherwise. In WorkBrief most lists are exactly
      // these two shapes (fcmTokens, requiredTools, assignedUserIds).
      final inner = f.itemSpec;
      if (inner != null) {
        if (inner.type == FieldType.string || inner.type == FieldType.ref) {
          base = 'List<String>';
        } else {
          base = 'List<dynamic>';
        }
      } else {
        base = 'List<dynamic>';
      }
    case FieldType.map:
      base = 'Map<String, dynamic>';
  }

  // Required + default → non-nullable (the constructor enforces required).
  // Optional → nullable.
  // primaryKey → non-nullable.
  if (f.optional && !f.required && !f.primaryKey) {
    return '$base?';
  }
  return base;
}

String _dartLiteral(dynamic value, FieldSpec f, String className) {
  if (value == null) return 'null';
  if (value is bool) return value.toString();
  if (value is num) return value.toString();
  if (value is List) {
    if (value.isEmpty) return 'const []';
    final items = value.map((v) => _dartLiteral(v, f, className)).join(', ');
    return 'const [$items]';
  }
  if (f.type == FieldType.enum_) {
    final enumName = _enumNameFor(className, f.name);
    return '$enumName.$value';
  }
  // strings — quote and escape minimally
  final s = value.toString().replaceAll('\\', '\\\\').replaceAll("'", "\\'");
  return "'$s'";
}

String _toJsonExpr(String access, FieldSpec f) {
  switch (f.type) {
    case FieldType.dateTime:
      return f.optional && !f.required
          ? '$access?.toIso8601String()'
          : '$access.toIso8601String()';
    case FieldType.enum_:
      return f.optional && !f.required ? '$access?.name' : '$access.name';
    default:
      return access;
  }
}

String _fromJsonExpr(String expr, FieldSpec f, String className) {
  final isOpt = f.optional && !f.required && !f.primaryKey;
  final defaultLiteral = f.defaultValue != null
      ? _dartLiteral(f.defaultValue, f, className)
      : null;

  String coreFor(String src, String castType) {
    switch (f.type) {
      case FieldType.string:
      case FieldType.ref:
        return '$src as String${isOpt ? '?' : ''}';
      case FieldType.int_:
        return '($src as num${isOpt ? '?' : ''})${isOpt ? '?' : ''}.toInt()';
      case FieldType.double_:
        return '($src as num${isOpt ? '?' : ''})${isOpt ? '?' : ''}.toDouble()';
      case FieldType.bool_:
        return '$src as bool${isOpt ? '?' : ''}';
      case FieldType.dateTime:
        return isOpt
            ? '$src == null ? null : DateTime.parse($src as String)'
            : 'DateTime.parse($src as String)';
      case FieldType.enum_:
        final enumName = _enumNameFor(className, f.name);
        return isOpt
            ? '$src == null ? null : $enumName.values.byName($src as String)'
            : '$enumName.values.byName($src as String)';
      case FieldType.list:
        // List<String> or List<dynamic>.
        final inner = f.itemSpec;
        if (inner != null &&
            (inner.type == FieldType.string || inner.type == FieldType.ref)) {
          return isOpt
              ? '($src as List?)?.cast<String>()'
              : '($src as List).cast<String>()';
        }
        return isOpt
            ? '($src as List?)?.cast<dynamic>()'
            : '($src as List).cast<dynamic>()';
      case FieldType.map:
        return isOpt
            ? '($src as Map?)?.cast<String, dynamic>()'
            : '($src as Map).cast<String, dynamic>()';
    }
  }

  if (defaultLiteral != null) {
    // For fields with defaults: read or fall back to default.
    final readExpr = coreFor(expr, '');
    if (f.type == FieldType.list || f.type == FieldType.map) {
      return '$expr == null ? $defaultLiteral : $readExpr';
    }
    return '$expr == null ? $defaultLiteral : $readExpr';
  }

  return coreFor(expr, '');
}

/// Multi-collection convenience — emits one model file per collection
/// keyed by the suggested filename. Caller writes them to disk.
Map<String, String> generateAllDartModels(
  Spec spec, {
  String? sourceFile,
}) {
  final out = <String, String>{};
  for (final c in spec.collections.values) {
    final fileName = _fileNameFor(c.name);
    out[fileName] = generateDartModel(c, sourceFile: sourceFile);
  }
  return out;
}

String _fileNameFor(String collectionName) {
  // workBriefs → work_brief.dart
  final snake = collectionName.replaceAllMapped(
    RegExp(r'[A-Z]'),
    (m) => '_${m.group(0)!.toLowerCase()}',
  );
  // strip trailing 's' for singular naming convention
  final singular = snake.endsWith('s') ? snake.substring(0, snake.length - 1) : snake;
  return '$singular.dart';
}
