import '../spec/spec.dart';

/// Generates `lib/firepack/paths.dart` — typed Firestore-collection-name
/// constants. One static-const String per declared collection.
///
/// **Why:** generated repositories reference collection paths via
/// `FirestorePaths.<name>`. Until M10 this file was hand-written by
/// every consumer (despite the README implying otherwise) — a real
/// promise gap. firepack now owns it.
///
/// **Example output for**
/// ```yaml
/// collections:
///   posts: { ... }
///   comments: { ... }
/// ```
///
/// **becomes:**
/// ```dart
/// class FirestorePaths {
///   FirestorePaths._();
///
///   static const String posts = 'posts';
///   static const String comments = 'comments';
/// }
/// ```
///
/// Returns null only when the spec declares no collections (which a
/// well-formed spec never does).
String? generateFirestorePathsFile(Spec spec, {String? sourceFile}) {
  if (spec.collections.isEmpty) return null;

  final buf = StringBuffer();
  buf.writeln(_header(sourceFile));
  buf.writeln();
  buf.writeln('/// Typed Firestore collection paths. Repository codegen');
  buf.writeln('/// references `FirestorePaths.<name>` so a renamed collection');
  buf.writeln('/// in the spec breaks the build, not the runtime.');
  buf.writeln('class FirestorePaths {');
  buf.writeln('  FirestorePaths._();');

  for (final c in spec.collections.values) {
    buf.writeln();
    buf.writeln("  static const String ${c.name} = '${c.name}';");
  }

  buf.writeln('}');
  return buf.toString();
}

String _header(String? sourceFile) {
  final src = sourceFile ?? 'firepack.yaml';
  return '''// GENERATED by firepack — do not edit.
// Source: $src
//
// Regenerate via:
//   dart run firepack:firepack regen --target paths --spec <path>
//
// Hand-edits here are overwritten on the next `firepack regen`.''';
}
