/// Generates `lib/firepack/firestore_provider.dart` — a single Riverpod
/// `Provider<FirebaseFirestore>` that every generated repository depends
/// on for its FirebaseFirestore instance.
///
/// **Why:** Repository-Providers used to bake in
/// `FirebaseFirestore.instance` directly, which made swapping a fake
/// (for tests, multi-DB, or staging endpoints) require an override of
/// every single repo provider. With this seam, consumers override
/// `firestoreProvider` once and every repo follows.
///
/// **Output:**
/// ```dart
/// final firestoreProvider = Provider<FirebaseFirestore>(
///   (_) => FirebaseFirestore.instance,
/// );
/// ```
String generateFirestoreProviderFile({String? sourceFile}) {
  final src = sourceFile ?? 'firepack.yaml';
  return '''// GENERATED by firepack — do not edit.
// Source: $src
//
// Regenerate via:
//   dart run firepack:firepack regen --target firestore_provider --spec <path>
//
// Hand-edits here are overwritten on the next `firepack regen`.

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// Single-seam Provider for FirebaseFirestore.
///
/// Override in tests / multi-DB / staging environments:
/// ```dart
/// ProviderScope(
///   overrides: [
///     firestoreProvider.overrideWithValue(fakeFirestore),
///   ],
///   child: const MyApp(),
/// )
/// ```
///
/// Every generated repository depends on this provider — overriding it
/// once swaps the underlying instance for all of them.
final firestoreProvider = Provider<FirebaseFirestore>(
  (_) => FirebaseFirestore.instance,
);
''';
}
