import '../spec/spec.dart';

/// Generates `firestore.rules` from a parsed [Spec].
///
/// **Output structure:**
///   rules_version = '2';
///   service cloud.firestore {
///     match /databases/{database}/documents {
///       <generated helpers>
///       <per-collection match blocks, in spec order>
///       <default-deny tail>
///     }
///   }
///
/// **Helper expansion** — the spec uses tokens (`signedIn`, `tenantSelf`,
/// `isAdmin`, …) that the generator translates to actual Firestore-rule
/// expressions. The same tokens are used in every collection so they
/// translate consistently.
///
/// **Verbatim escape** — for rule fragments the spec language doesn't
/// model yet (e.g. workers can update only `workBriefs.status`), a
/// collection's `rules:` block may include `verbatim: |\n  …` raw text.
/// The generator appends that text inside the match block, after the
/// generated `allow` lines.
String generateRulesFile(Spec spec) {
  final buf = StringBuffer();
  buf.writeln(_header);
  buf.writeln(_helpers);

  for (final c in spec.collections.values) {
    if (c.rules == null && (c.fields.isEmpty)) continue;
    if (c.rules == null) continue; // skip collections without rules block

    buf.writeln(_emitMatchBlock(c));
  }

  buf.writeln(_defaultDeny);
  buf.writeln(_footer);
  return buf.toString();
}

const _header = '''rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {''';

const _helpers = '''
    // Generated by firepack — do not edit. Source:
    // ~/work/moinsen/opensource/firepack/example/<project>.firepack.yaml

    function isSignedIn() {
      return request.auth != null;
    }

    // Single source for the caller's user doc. Firestore caches get()
    // results within a single rule evaluation, so calling userDoc()
    // from multiple helpers below results in ONE billable read per
    // request.
    function userDoc() {
      return get(/databases/\$(database)/documents/users/\$(request.auth.uid)).data;
    }

    function getUserOrgId() {
      return userDoc().organizationId;
    }

    function getUserRole() {
      return userDoc().role;
    }

    function isAdmin() {
      return userDoc().role == 'admin';
    }

    function isSupervisorOrAdmin() {
      let role = userDoc().role;
      return role == 'admin' || role == 'supervisor';
    }
''';

const _defaultDeny = '''
    // Secure everything else by default
    match /{document=**} {
      allow read, write: if false;
    }''';

const _footer = '''  }
}''';

/// Emits one `match /<col>/{<id>} { … }` block for a collection.
String _emitMatchBlock(CollectionSpec c) {
  final buf = StringBuffer();
  final idVar = _idVarFor(c);
  buf.writeln();
  buf.writeln('    match /${c.name}/{$idVar} {');

  final r = c.rules!;
  if (r.read != null) {
    buf.writeln('      allow read: if ${_expandExpr(r.read!, c, ctx: _ExprCtx.read, idVar: idVar)};');
  }
  if (r.create != null) {
    buf.writeln('      allow create: if ${_expandExpr(r.create!, c, ctx: _ExprCtx.create, idVar: idVar)};');
  }
  for (final clause in r.update) {
    buf.writeln('      allow update: if ${_expandUpdateClause(clause, c, idVar: idVar)};');
  }
  if (r.delete != null) {
    final v = r.delete!.toLowerCase();
    if (v == 'false') {
      buf.writeln('      allow delete: if false;');
    } else if (v == 'true') {
      buf.writeln('      allow delete: if true;');
    } else {
      buf.writeln('      allow delete: if ${_expandExpr(r.delete!, c, ctx: _ExprCtx.delete, idVar: idVar)};');
    }
  }

  if (r.verbatim != null && r.verbatim!.trim().isNotEmpty) {
    // Escape-hatch for rules our token expander doesn't capture yet
    // (e.g. workers updating only `workBriefs.status`). The author's
    // raw Firestore-rule text is appended inside the match block,
    // indented to match.
    final lines = r.verbatim!.trimRight().split('\n');
    for (final line in lines) {
      // Preserve relative indent the author wrote, prefix with 6 spaces
      // to match the inside-match-block depth.
      final trimmedRight = line.replaceAll(RegExp(r'\s+$'), '');
      buf.writeln(trimmedRight.isEmpty ? '' : '      $trimmedRight');
    }
  }

  buf.writeln('    }');
  return buf.toString();
}

/// `users` → `userId`; everything else → `<col>Id` singularised loosely.
/// Falls back to `id` for unfamiliar names.
String _idVarFor(CollectionSpec c) {
  // Common Dart-style camelCase: stripping a trailing 's' is a passable
  // heuristic for 80% of cases (users → userId, workBriefs → workBriefId,
  // teams → teamId). Edge cases (auditLogs → auditLogId) work fine too.
  final base = c.name.endsWith('s')
      ? c.name.substring(0, c.name.length - 1)
      : c.name;
  return '${base}Id';
}

enum _ExprCtx { read, create, update, delete }

/// Translates spec helper tokens into Firestore rule expressions.
///
/// We deliberately keep this simple text-replace today — we do *not*
/// build an AST. The tokens are short, well-known, and the spec is
/// authored by hand. If a token isn't in the table we leave it alone
/// so the rules-audit catches a typo loudly rather than silently
/// emitting a broken rule.
String _expandExpr(
  String src,
  CollectionSpec c, {
  required _ExprCtx ctx,
  required String idVar,
}) {
  final tenant = c.tenant;
  // For mutations (create/update/delete) the new doc lives in
  // `request.resource.data`; for reads it's `resource.data`.
  final tenantField =
      ctx == _ExprCtx.create
          ? 'request.resource.data.$tenant'
          : 'resource.data.$tenant';

  var s = src;
  // Replacements ordered longest-first so multi-token combos win over
  // single-tokens (e.g. `tenantMatchOrAdmin` before `tenant`).
  s = s.replaceAll(
    'tenantMatchOrAdmin',
    tenant != null ? '($tenantField == getUserOrgId() || isAdmin())' : 'isAdmin()',
  );
  s = s.replaceAll(
    'tenantSelf',
    tenant != null ? '$tenantField == getUserOrgId()' : 'true',
  );
  s = s.replaceAll('isSupervisorOrAdmin', 'isSupervisorOrAdmin()');
  s = s.replaceAll('supervisorOrAdmin', 'isSupervisorOrAdmin()');
  s = s.replaceAll('isAdmin', 'isAdmin()');
  s = s.replaceAll(RegExp(r'\bself\b'), 'request.auth.uid == $idVar');
  s = s.replaceAll('signedIn', 'isSignedIn()');

  // Helper-of-helper: `selfOr(<expr>)` → `(self || <expr>)` already
  // expanded above because `self` got replaced; the outer wrap stays.
  return s;
}

/// One update-clause becomes one `allow update: if …` line.
/// Field-allowlist (`fields: name,email,…`) becomes
/// `request.resource.data.diff(resource.data).affectedKeys().hasOnly([…])`.
String _expandUpdateClause(
  RuleClause clause,
  CollectionSpec c, {
  required String idVar,
}) {
  final role = _expandExpr(clause.roleExpr, c, ctx: _ExprCtx.update, idVar: idVar);
  final fields = clause.fieldsExpr.trim();

  if (fields == 'all' || fields.isEmpty) {
    return role;
  }

  // Comma-separated list of allowed-changing fields.
  final list = fields
      .split(',')
      .map((f) => f.trim())
      .where((f) => f.isNotEmpty)
      .map((f) => "'$f'")
      .join(', ');
  return '$role && '
      'request.resource.data.diff(resource.data).affectedKeys().hasOnly([$list])';
}
