import '../spec/spec.dart';

/// Generates `lib/firepack/storage_paths.dart` — typed helpers for
/// Cloud Storage path construction. One method per declared bucket,
/// taking the path-template variables as named parameters.
///
/// **Why:** Hand-typed Storage paths drift across upload code, read
/// code, security rules, and Cloud Functions. With this generator,
/// the spec's `storage:` block is the single source of truth.
///
/// **Example output for**
/// ```yaml
/// storage:
///   evidenceFiles:
///     path: "evidence/{organizationId}/{workBriefId}/{evidenceId}"
///     tenant: organizationId
///     contentTypes: [image/jpeg, image/png]
/// ```
///
/// **becomes:**
/// ```dart
/// class StoragePaths {
///   static String evidenceFiles({
///     required String organizationId,
///     required String workBriefId,
///     required String evidenceId,
///   }) => 'evidence/$organizationId/$workBriefId/$evidenceId';
///
///   static const evidenceFilesContentTypes = ['image/jpeg', 'image/png'];
/// }
/// ```
///
/// Returns null when the spec declares no storage buckets.
String? generateStoragePathsFile(Spec spec, {String? sourceFile}) {
  if (spec.storage.isEmpty) return null;

  final buf = StringBuffer();
  buf.writeln(_header(sourceFile));
  buf.writeln();
  buf.writeln('/// Typed Cloud Storage path helpers, one method per declared');
  buf.writeln(
      '/// bucket in the firepack spec. Use these instead of hand-typed');
  buf.writeln('/// strings — drift between upload code, read code, and rules');
  buf.writeln('/// becomes impossible.');
  buf.writeln('class StoragePaths {');
  buf.writeln('  const StoragePaths._();');

  for (final s in spec.storage.values) {
    buf.writeln();
    _emitBucketHelper(buf, s);
  }

  buf.writeln('}');
  return buf.toString();
}

void _emitBucketHelper(StringBuffer buf, StorageBucket bucket) {
  final params = _extractPathParams(bucket.path);

  // method name = bucket name
  buf.writeln('  /// Path for `${bucket.name}` bucket. Template:');
  buf.writeln('  /// `${bucket.path}`');
  if (bucket.tenant != null) {
    buf.writeln('  /// Tenant variable: `${bucket.tenant}`.');
  }

  if (params.isEmpty) {
    buf.writeln('  static String ${bucket.name}() => \'${bucket.path}\';');
  } else {
    buf.writeln('  static String ${bucket.name}({');
    for (final p in params) {
      buf.writeln('    required String $p,');
    }
    buf.writeln('  }) => \'${_interpolate(bucket.path, params)}\';');
  }

  if (bucket.contentTypes.isNotEmpty) {
    final list = bucket.contentTypes.map((c) => "'$c'").join(', ');
    buf.writeln();
    buf.writeln('  /// MIME types accepted by the `${bucket.name}` bucket.');
    buf.writeln(
        '  static const List<String> ${bucket.name}ContentTypes = [$list];');
  }
}

/// Extracts `{varName}` placeholders from a path template, in order.
/// Duplicates dedupe — `evidence/{orgId}/{orgId}` yields one param.
List<String> _extractPathParams(String template) {
  final seen = <String>{};
  final ordered = <String>[];
  final matches = RegExp(r'\{([a-zA-Z_][a-zA-Z0-9_]*)\}').allMatches(template);
  for (final m in matches) {
    final name = m.group(1)!;
    if (seen.add(name)) ordered.add(name);
  }
  return ordered;
}

/// Replaces `{var}` with `$var` for Dart string interpolation.
String _interpolate(String template, List<String> params) {
  var out = template;
  for (final p in params) {
    out = out.replaceAll('{$p}', '\$$p');
  }
  return out;
}

String _header(String? sourceFile) {
  final src = sourceFile ?? 'firepack.yaml';
  return '''// GENERATED by firepack — do not edit.
// Source: $src
//
// Regenerate via:
//   firepack regen --target storage --spec <path>
//
// To change a Storage bucket's path or content types, edit the spec,
// then regenerate. Hand-edits here are overwritten on the next run.''';
}
